# Generated by Django 4.0.3 on 2022-03-31 13:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_taskmodel_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskModel',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='TaskListModel',
            new_name='TaskList',
        ),
    ]
